-- importazione dati traffico leuven
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-05-01_05-00-00/raw_data/9000008590.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-05-01_05-00-00/raw_data/9000008622.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-05-01_05-00-00/raw_data/9000008623.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-05-01_05-00-00/raw_data/9000008629.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-05-01_05-00-00/raw_data/9000008693.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-05-01_05-00-00/raw_data/9000008720.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);

INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-06-01_05-00-00/raw_data/9000008590.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-06-01_05-00-00/raw_data/9000008622.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-06-01_05-00-00/raw_data/9000008623.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-06-01_05-00-00/raw_data/9000008629.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-06-01_05-00-00/raw_data/9000008693.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-06-01_05-00-00/raw_data/9000008720.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);

INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-09-01_05-00-00/raw_data/9000008590.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-09-01_05-00-00/raw_data/9000008622.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-09-01_05-00-00/raw_data/9000008623.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-09-01_05-00-00/raw_data/9000008629.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-09-01_05-00-00/raw_data/9000008693.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-09-01_05-00-00/raw_data/9000008720.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);

INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-10-01_05-00-00/raw_data/9000008590.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-10-01_05-00-00/raw_data/9000008622.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-10-01_05-00-00/raw_data/9000008623.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-10-01_05-00-00/raw_data/9000008629.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-10-01_05-00-00/raw_data/9000008693.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-10-01_05-00-00/raw_data/9000008720.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);

INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-11-01_05-00-00/raw_data/9000008590.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-11-01_05-00-00/raw_data/9000008622.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-11-01_05-00-00/raw_data/9000008623.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-11-01_05-00-00/raw_data/9000008629.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-11-01_05-00-00/raw_data/9000008693.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-11-01_05-00-00/raw_data/9000008720.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);

INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-12-01_05-00-00/raw_data/9000008590.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-12-01_05-00-00/raw_data/9000008622.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-12-01_05-00-00/raw_data/9000008623.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-12-01_05-00-00/raw_data/9000008629.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-12-01_05-00-00/raw_data/9000008693.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2025-12-01_05-00-00/raw_data/9000008720.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);

INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-01-01_05-00-00/raw_data/9000008590.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-01-01_05-00-00/raw_data/9000008622.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-01-01_05-00-00/raw_data/9000008623.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-01-01_05-00-00/raw_data/9000008629.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-01-01_05-00-00/raw_data/9000008693.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-01-01_05-00-00/raw_data/9000008720.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);

INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-02-01_05-00-00/raw_data/9000008590.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-02-01_05-00-00/raw_data/9000008622.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-02-01_05-00-00/raw_data/9000008623.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-02-01_05-00-00/raw_data/9000008629.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-02-01_05-00-00/raw_data/9000008693.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);
INSERT INTO public.batch_job_task_queue (id_batch, json_param, status, date_ins, date_mod, note) VALUES( 1, '{"items": [{"key": "bucket", "value": "urbreath-public-repo", "type": "STRING"}, {"key": "objectKey", "value": "Leuven/Mobility/KPIs/2026-02-01_05-00-00/raw_data/9000008720.csv", "type": "STRING"}]}'::json, 0, now(), null, NULL);