spring:
  datasource:
    url: jdbc:postgresql://127.0.1.1:5433/urbreath_dev
    username: external_user
    password: external_pass

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

minio:
    endpoint: https://minio-api-dev.urbreath.tech/
    access-key: Municipia
    secret-key: zS3fx4zeECPuc4K
  
  
  