spring:
  datasource:
    url: jdbc:postgresql://188.34.141.13:57708/urbreath_dev?reWriteBatchedInserts=true
    username: ENC(a7i6s+RMohdZwr8FP6x+JHgbEDlwg/+m/NSvWDmKhBOHhKpjH9V+lTNHqS1HRjuc)
    password: ENC(1CyCGXbJC1qVCSWJAN++dQiaunx7SKzmr+QU+R2VzGJqcgvNCjrIRSNt0EpHlvuR)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 540000          
      keepalive-time: 30000        
      validation-timeout: 5000
      connection-test-query: SELECT 1
      data-source-properties:
         rewriteBatchedStatements: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

minio:
    endpoint: https://minio-api-dev.urbreath.tech/
    access-key: ENC(kaas+FptqF3ldcOhOl67cevgG6XvkvELSr1GUXkY5FpQQONV/KkmINdGsyIoj7XU)
    secret-key: ENC(gAPJR5i+7GDATUjwCN8ChkfcVjptAtT0jjoMiKyUQ/meS/pOYCD+dYUZ+ZpFMNn6)
  
  
Jasypt:
  encryptor:
    password: 3DhnYMX8IuJpTASR

app:
  access-key: Municipia
  secret-key: zS3fx4zeECPuc4K

wms:
  base-url: https://urbreath.simena.red/wms/wms/
  cities:
    MADRID:
      bbox: '-413371.4489662349%2C4916429.659302536%2C-412148.4565136721%2C4917652.651755099'
      timezone: Europe%2FMadrid
      i: 304
      j: 135
    LEUVEN:
      bbox: '525886.7546020113%2C6599267.274028977%2C528332.739507137%2C6601713.258934103'
      timezone: Europe%2FBrussels
      i: 304
      j: 135
    CLUJ:
      bbox: '2622095.8182946853%2C5899715.591163045%2C2631879.757915188%2C5909499.530783547'
      timezone: Europe%2FBucharest
      i: 69
      j: 143
    TALLIN:
      bbox: '2759070.972981721%2C8267428.979324663%2C2768854.912602224%2C8277212.918945165'
      timezone: Europe%2FTallin
      i: 278
      j: 364
  
  call-types:
    mintemperature:
      layer: FIC_SAMPLE_PROB_TMIN_R00R12_URB
      key: FIC_THRESHOLD_TMIN_URB
      measures: [-5, 0, 5, 10]
    maxtemperature:
      layer: FIC_SAMPLE_PROB_TMAX_R00R12_URB
      key: FIC_THRESHOLD_TMAX_URB
      measures: [20, 25, 30, 35, 40]
    precipitation:
      layer: FIC_SAMPLE_PROB_PRECIPITATION_24H_R00R12_URB
      key: FIC_THRESHOLD_PRECIPITATION_24H_URB
      measures: [0, 5, 10, 20, 30, 50]
    wind:
      layer: FIC_SAMPLE_PROB_GUSTMAX_R00R12_URB
      key: FIC_THRESHOLD_GUSTMAX_URB
      measures: [10, 20, 30, 50]

  sensors:
    MADRID:
      FIC_THRESHOLD_TMIN_URB: MADRID_TMIN_SENSOR
      FIC_THRESHOLD_TMAX_URB: MADRID_TMAX_SENSOR
      FIC_THRESHOLD_PRECIPITATION_24H_URB: MADRID_PRECIP_SENSOR
      FIC_THRESHOLD_GUSTMAX_URB: MADRID_WIND_SENSOR
    LEUVEN:
      FIC_THRESHOLD_TMIN_URB: LEUVEN_TMIN_SENSOR
      FIC_THRESHOLD_TMAX_URB: LEUVEN_TMAX_SENSOR
      FIC_THRESHOLD_PRECIPITATION_24H_URB: LEUVEN_PRECIP_SENSOR
      FIC_THRESHOLD_GUSTMAX_URB: LEUVEN_WIND_SENSOR
    CLUJ:
      FIC_THRESHOLD_TMIN_URB: CLUJ_TMIN_SENSOR
      FIC_THRESHOLD_TMAX_URB: CLUJ_TMAX_SENSOR
      FIC_THRESHOLD_PRECIPITATION_24H_URB: CLUJ_PRECIP_SENSOR
      FIC_THRESHOLD_GUSTMAX_URB: CLUJ_WIND_SENSOR
    TALLIN:
      FIC_THRESHOLD_TMIN_URB: TALLIN_TMIN_SENSOR
      FIC_THRESHOLD_TMAX_URB: TALLIN_TMAX_SENSOR
      FIC_THRESHOLD_PRECIPITATION_24H_URB: TALLIN_PRECIP_SENSOR
      FIC_THRESHOLD_GUSTMAX_URB: TALLIN_WIND_SENSOR

logging:
  level:
    eu.urbreathdsjobs.job.JobWSMScheduler: INFO
    eu.urbreathdsjobs.job.WmsImportTasklet: INFO
    eu.urbreathdsjobs.client.wms.WmsHttpClientService: INFO
    eu.urbreathdsjobs.client.wms.WmsResponseHandlerService: INFO